openapi: 3.0.1
info:
  title: Movie Suggestion
  version: v1
servers:
  - url: http://localhost:8080/
    description: Generated server url
paths:
  /movies/{country}/{city}:
    get:
      tags:
        - movie-suggestion-controller
      operationId: findMoviesByTemperature
      parameters:
        - name: country
          in: path
          required: true
          schema:
            type: string
            enum:
              - BRAZIL
              - CHINA
              - CANADA
              - MADAGASCAR
              - GREENLAND
        - name: city
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieResponse'
components:
  schemas:
    MovieResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        originalTitle:
          type: string
        overview:
          type: string
        originalLanguage:
          type: string
        adult:
          type: boolean
        releaseDate:
          type: string
          format: date
